import Head from 'next/head'

import Header from '../components/Header'
import Banner from '../components/Banner'
import SmallCard from '../components/SmallCard'
import MediumCard from '../components/MediumCard'
import LargeCard from '../components/LargeCard'
import Footer from '../components/Footer'

const sectionTitleStyle = 'text-4xl font-bold pb-6 text-gray-900'

export default function Home({ exploreData, liveAnywhereData }) {
  return (
    <div>
      <Head>
        <title>Airbnb Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Banner />

      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='py-6'>
          <h2 className={sectionTitleStyle}>Explore Nearby</h2>

          {/* Pull some data from a server*/}
          <div className='grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4 align-middle mb-10'>
            {exploreData?.map((item, index) => (
              <SmallCard
                key={index}
                img={item.img}
                location={item.location}
                distance={item.distance}
              />
            ))}
          </div>

          <h2 className={sectionTitleStyle}>Live Anywhere</h2>

          <div className='grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4 mb-10'>
            {liveAnywhereData?.map((item, index) => (
              <MediumCard key={index} img={item.img} title={item.title} />
            ))}
          </div>

          <LargeCard
            img='https://links.papareact.com/4cj'
            title='The Greatest Outdoors'
            description='Wishslists curated by Airbnb.'
            buttonText='Get inspired'
          />
        </section>
      </main>
      <Footer/>
    </div>
  )
}

export async function getServerSideProps() {
  const smallCardData = await fetch('https://www.jsonkeeper.com/b/4G1G')
  const exploreData = await smallCardData.json()

  const mediumCardData = await fetch('https://www.jsonkeeper.com/b/VHHT')
  const liveAnywhereData = await mediumCardData.json()

  return {
    props: {
      exploreData,
      liveAnywhereData
    }
  }
}
